"""empty message

Revision ID: bbc65942e9a2
Revises: cae5e85415c2
Create Date: 2020-08-06 21:41:04.179460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc65942e9a2'
down_revision = 'cae5e85415c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('confirmed_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed_on')
    op.drop_column('user', 'confirmed')
    # ### end Alembic commands ###
